stages:
  - build
  - test
  - deploy

.staging:
  only:
    refs:
      - develop
  tags:
    - docker
    - staging

.production:
  only:
    refs:
      - master
    # - /^release-.*$/
    # except:
    # - branches
  tags:
    - docker
    - production
    - domestic

.build:
  stage: build
  script:
#    - cat ${PROJECT_ENV} > project/.env
    - docker-compose build
  only:
    changes:
      - requirements.txt
      - Dockerfile


.test:
  stage: test
  script:
    - docker-compose run --rm django-app python manage.py test
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov

.deploy:
  stage: deploy
  script:
    - docker-compose up -d

build_staging:
  environment:
    name: staging
  extends:
    - .build
    - .staging

build_production:
  environment:
    name: production
  extends:
    - .build
    - .production
