version: '3.4'

services:
  test-app:
    entrypoint: [ "/entrypoint.sh" ]
    build:
      context: .
      dockerfile: Dockerfile
      target: test_build
    environment:
      - DEBUG=True
      - SECRET_KEY = 'secret_key_for_test'
      - ALLOWED_HOSTS = '*'
      - DB_ENGINE = 'django.db.backends.postgresql'
      - DB_NAME = 'test_db'
      - DB_HOST = 'test_db'
      - DB_USER = 'test_user'
      - DB_PASS = 'test_password'
      - CACHE_BACKEND = 'django.core.cache.backends.memcached.PyMemcacheCache'
      - CACHE_HOST = '192.168.2.21:11211'
      - CELERY_USER = ''
      - CELERY_PASS = ''
      - CELERY_HOST = ''
      - INSTA_FOLLOW_BASE_URL = ''
      - INSTA_FOLLOW_ORDER_LIMIT = 0
      - INSTA_FOLLOW_BASE_URL = 'https://instaflw.yourblueapi.com'
      - INSTA_FOLLOW_ORDER_LIMIT = 2
      - SIGN_UP_PROXY_IP=''
      - SIGN_UP_PROXY_PORT=10000
      - SIGN_UP_PROXY_USER=''
      - SIGN_UP_PROXY_PASS=''

    depends_on:
      - test-db

  test-db:
    image: postgres:10.0-alpine
    hostname: test_db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db


networks:
  test-network: