version: '3.4'

services:
  test-app:
    entrypoint: [ "/entrypoint.sh" ]
    context: .
      dockerfile: Dockerfile
      target: deploy_test
    env_file: ${PROJECT_ENV}
    volumes:
      - ./project:/app
    depends_on:
      - test-db

  test-db:
    image: postgres:10.0-alpine
    hostname: test_db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db